"""initial domain models

Revision ID: 91004fffe85d
Revises: 
Create Date: 2026-02-11 08:19:31.933918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel  # noqa: F401

# revision identifiers, used by Alembic.
revision: str = '91004fffe85d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('auditlog',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('actor_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('auditlog', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_auditlog_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_auditlog_event_type'), ['event_type'], unique=False)

    op.create_table('outboxevent',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('event_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aggregate_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('aggregate_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('idempotency_key', sa.String(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    with op.batch_alter_table('outboxevent', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_outboxevent_aggregate_id'), ['aggregate_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_outboxevent_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_outboxevent_status'), ['status'], unique=False)

    op.create_table('protocol',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('file_uri', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('page_count', sa.Integer(), nullable=True),
    sa.Column('quality_score', sa.Float(), nullable=True),
    sa.Column('metadata_', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('protocol', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_protocol_status'), ['status'], unique=False)

    op.create_table('review',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('reviewer_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('target_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('action', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('before_value', sa.JSON(), nullable=True),
    sa.Column('after_value', sa.JSON(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_review_reviewer_id'), ['reviewer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_review_target_id'), ['target_id'], unique=False)

    op.create_table('criteriabatch',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('protocol_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('extraction_model', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['protocol_id'], ['protocol.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('criteriabatch', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_criteriabatch_protocol_id'), ['protocol_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_criteriabatch_status'), ['status'], unique=False)

    op.create_table('criteria',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('batch_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criteria_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('temporal_constraint', sa.JSON(), nullable=True),
    sa.Column('conditions', sa.JSON(), nullable=True),
    sa.Column('numeric_thresholds', sa.JSON(), nullable=True),
    sa.Column('assertion_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('source_section', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('review_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['batch_id'], ['criteriabatch.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('criteria', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_criteria_batch_id'), ['batch_id'], unique=False)

    op.create_table('entity',
    sa.Column('id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('criteria_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('entity_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('text', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('span_start', sa.Integer(), nullable=True),
    sa.Column('span_end', sa.Integer(), nullable=True),
    sa.Column('umls_cui', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('snomed_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('preferred_term', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('grounding_confidence', sa.Float(), nullable=True),
    sa.Column('grounding_method', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('review_status', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('context_window', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['criteria_id'], ['criteria.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_entity_criteria_id'), ['criteria_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_entity_entity_type'), ['entity_type'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('entity', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_entity_entity_type'))
        batch_op.drop_index(batch_op.f('ix_entity_criteria_id'))

    op.drop_table('entity')
    with op.batch_alter_table('criteria', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_criteria_batch_id'))

    op.drop_table('criteria')
    with op.batch_alter_table('criteriabatch', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_criteriabatch_status'))
        batch_op.drop_index(batch_op.f('ix_criteriabatch_protocol_id'))

    op.drop_table('criteriabatch')
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_review_target_id'))
        batch_op.drop_index(batch_op.f('ix_review_reviewer_id'))

    op.drop_table('review')
    with op.batch_alter_table('protocol', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_protocol_status'))

    op.drop_table('protocol')
    with op.batch_alter_table('outboxevent', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_outboxevent_status'))
        batch_op.drop_index(batch_op.f('ix_outboxevent_event_type'))
        batch_op.drop_index(batch_op.f('ix_outboxevent_aggregate_id'))

    op.drop_table('outboxevent')
    with op.batch_alter_table('auditlog', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_auditlog_event_type'))
        batch_op.drop_index(batch_op.f('ix_auditlog_actor_id'))

    op.drop_table('auditlog')
    # ### end Alembic commands ###
