#!/usr/bin/env bash
set -euo pipefail

# ==============================================================================
# GemmaCrit Local Model Setup
# Detects hardware, installs Ollama, pulls models, configures .env.local
# ==============================================================================

echo "=== GemmaCrit Local Model Setup ==="
echo ""

# --- 1. Detect hardware ---
echo "[1/7] Detecting hardware..."
if [[ "$(uname -s)" == "Darwin" ]]; then
    if [[ "$(uname -m)" == "arm64" ]]; then
        HW="apple_silicon"
        echo "  Detected: Apple Silicon (M-series)"
    else
        HW="cpu"
        echo "  Detected: Intel Mac (CPU only)"
    fi
elif command -v nvidia-smi &>/dev/null; then
    HW="nvidia"
    echo "  Detected: NVIDIA GPU"
    nvidia-smi --query-gpu=name,memory.total --format=csv,noheader 2>/dev/null || true
else
    HW="cpu"
    echo "  Detected: CPU only"
fi
echo ""

# --- 2. Check Ollama ---
echo "[2/7] Checking Ollama installation..."
if command -v ollama &>/dev/null; then
    echo "  Ollama is installed: $(ollama --version 2>/dev/null || echo 'version unknown')"
else
    echo "  Ollama not found. Installing..."
    if [[ "$(uname -s)" == "Darwin" ]]; then
        if command -v brew &>/dev/null; then
            brew install ollama
        else
            echo "  Please install Homebrew first, or install Ollama from https://ollama.ai"
            exit 1
        fi
    else
        curl -fsSL https://ollama.ai/install.sh | sh
    fi
    echo "  Ollama installed successfully."
fi
echo ""

# --- 3. Start Ollama serve ---
echo "[3/7] Starting Ollama server..."
if curl -s http://localhost:11434/api/tags &>/dev/null; then
    echo "  Ollama server already running."
else
    ollama serve &>/dev/null &
    OLLAMA_PID=$!
    echo "  Started Ollama server (PID: $OLLAMA_PID)"
    sleep 3
    if ! curl -s http://localhost:11434/api/tags &>/dev/null; then
        echo "  WARNING: Ollama server may not have started. Continuing anyway..."
    fi
fi
echo ""

# --- 4. Pull grounding model ---
echo "[4/7] Pulling grounding model..."
GROUNDING_MODEL="gemma2:9b"
echo "  Note: MedGemma 4B-IT is a gated HuggingFace model not yet available in Ollama."
echo "  Using $GROUNDING_MODEL as fallback (strong medical knowledge)."
echo "  To use MedGemma when GGUF becomes available:"
echo "    1. Download GGUF from HuggingFace"
echo "    2. Create Modelfile: FROM ./medgemma-4b-it.gguf"
echo "    3. ollama create medgemma -f Modelfile"
echo ""
ollama pull "$GROUNDING_MODEL"
echo ""

# --- 5. Pull extraction model ---
echo "[5/7] Pulling extraction model (JSON-capable)..."
if [[ "$HW" == "cpu" ]]; then
    EXTRACTION_MODEL="llama3.1:8b"
    echo "  CPU detected — using smaller model: $EXTRACTION_MODEL"
else
    EXTRACTION_MODEL="qwen2.5:14b"
    echo "  GPU detected — using: $EXTRACTION_MODEL"
fi
ollama pull "$EXTRACTION_MODEL"
echo ""

# --- 6. Write .env.local ---
echo "[6/7] Writing configuration to .env.local..."
ENV_FILE="$(cd "$(dirname "$0")/.." && pwd)/.env.local"
cat > "$ENV_FILE" <<EOF
# GemmaCrit Local Model Configuration
# Generated by setup-local-models.sh on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
MODEL_BACKEND=ollama
OLLAMA_BASE_URL=http://localhost:11434
OLLAMA_MODEL=${GROUNDING_MODEL}
OLLAMA_EXTRACTION_MODEL=${EXTRACTION_MODEL}
LOCAL_EXTRACTION_ENABLED=true
EOF
echo "  Written to: $ENV_FILE"
echo ""

# --- 7. Validate ---
echo "[7/7] Running validation..."
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
if [[ -f "$SCRIPT_DIR/validate-model-endpoint.py" ]]; then
    uv run python "$SCRIPT_DIR/validate-model-endpoint.py"
else
    echo "  Validation script not found. Doing basic check..."
    if curl -s http://localhost:11434/api/tags | python3 -c "import sys,json; models=json.load(sys.stdin).get('models',[]); print(f'  Found {len(models)} models: {[m[\"name\"] for m in models]}')" 2>/dev/null; then
        echo "  Ollama is running with models available."
    else
        echo "  WARNING: Could not verify Ollama models."
    fi
fi

echo ""
echo "=== Setup Complete ==="
echo ""
echo "To use local models:"
echo "  source .env.local"
echo "  # or add 'dotenv_path = \".env.local\"' to your .env"
echo ""
echo "To switch back to Gemini:"
echo "  unset MODEL_BACKEND OLLAMA_BASE_URL LOCAL_EXTRACTION_ENABLED"
